Avoid notify changes from background thread
java.lang.IllegalStateException: Cannot call this method while
RecyclerView is computing a layout or scrolling may throw if
notification is post from background thread